version: '3.5'

services:
  api-prod:
    build: .
    command: npm run start:prod
    volumes:
      - .:/app
    ports:
      - '${PORT}:${PORT}'
    networks:
      - backend
    env_file:
      - .env

  api-dev:
    build: .
    command: npm run start:dev
    volumes:
      - .:/app
    ports:
      - '${PORT}:${PORT}'
    networks:
      - backend
    env_file:
      - .env

  api-debug:
    build: .
    command: npm run start:debug
    volumes:
      - .:/app
    ports:
      - '${PORT}:${PORT}'
      - '9229:9229'
    networks:
      - backend
    env_file:
      - .env


networks:
  backend:
    name: drogaria_network
    driver: bridge
