import { CreateOrderDto } from '@core/application/dto/createOrder.dto';

export const defaultMockOrder: CreateOrderDto = {
  cdFilial: 0,
  cgcFilial: 'teste',
  dtEmissao: '2023-02-06 19:31:58.050',
  cliente: {
    nome: 'Ana Natália Beatriz da Silva',
    cpfCgc: '903.662.813-05',
    telefone: '(27)98905-5424',
    sexo: 'Masculino',
    dtNascimento: '1985-05-14',
    endereco: 'Rua Disavo',
    numero: '211',
    complemento: 'nao tem',
    cep: '29179-237',
    bairro: 'Centro da Serra',
    cidade: 'Serra',
    uf: 'ES',
    cidadeIBGE: 5,
    referencia: 'teste',
    email: 'ana_natalia_dasilva@molsanto.com',
    inscEstadual: 'teste',
    inscMunicipal: 'teste',
  },
  vlrProdutos: 5.99,
  vlrDescontos: 1.99,
  vlrFrete: 20.0,
  vlrOutros: 0,
  vlrTotal: 24.0,
  vlrTroco: 0,
  observacao: 'pagamento online',
  nrPedido: '2510',
  retirar: true,
  itens: [
    {
      cdProduto: 2310,
      cdBarrasProduto: 'teste123',
      quantidade: 10,
      vlrUnitario: 0.599,
      vlrDesconto: 0.199,
      vlrTotal: 4.0,
    },
  ],
};
