name: Node.js CI/CD

on:
  push:
    branches: ['main']

jobs:
  deploy-pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: installing pm2
        run: npm install pm2@latest -g

      - name: Building Node project
        run: npm run build --if-present

      - name: Deploy using ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          port: 22
          script: |
            cd /root/drogaria-service
            git pull origin main
            git status
            npm install
            npm run build
            pm2 restart drogaria-service
