name: Deploy with SSH

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install SSH key
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.PRIVATE_KEY }}

    - name: Login to remote server
      run: ssh -o StrictHostKeyChecking=no ${{ secrets.USERNAME }}@${{ secrets.HOST_IP }}

    - name: Pull latest changes from repository
      run: git pull

    - name: Build Docker image
      run: sudo docker build -t your-image-name .

    - name: SSH into server and deploy Docker container
      run: ssh ${{ secrets.USERNAME }}@${{ secrets.HOST_IP }} 'sudo docker compose -f drogaria-service/docker-compose.yml up -d'
