name: Node.js CI/CD

on:
  push:
    branches: ['master']

jobs:
  build-pipeline:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.19.0]

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Installing Node dependencies
        run: npm ci

      - name: Building Node project
        run: rm -rf dist && npm run build --if-present

  deploy-pipeline:
    runs-on: ubuntu-latest
    needs: build-pipeline

    steps:
    - name: Deploy using ssh
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.PRIVATE_KEY }}
        port: 22
        script: |
          cd /root/drogaria-service
          git pull origin master
          git status
          npm ci
          npm run build
          pm2 restart drogaria-service


